name: evaluateApi

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          entryPoint: 'sonar-scanner'
          args: |
            -Dsonar.organization=thedevfactory-pilot
            -Dsonar.projectKey=a-spriggs-m4ep4k3y_react_20472078-818a-4ee2-bf19-b7d34b2c2058_674cbfdf4f9b2ea96c2df01d_6754c02fd7161524b59ef2e0_6754c02fd7161524b59ef2df
            -Dsonar.branch.name=main
        env:
          SONAR_TOKEN: 65207c3be5d5ffb591719c8c5602be2548f1ad5a

  deploymentTesting:
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::426691418260:role/PullDeploymentTesting
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Run with Docker Compose
        run: |
          docker compose up --abort-on-container-exit
          
      - name: Cleanup
        if: always()
        run: docker compose down  